use AGENDA
go

CREATE DATABASE AGENDA
go

USE AGENDA
GO

CREATE TABLE PERSONAS
(
ID_PERSONAS INT NOT NULL PRIMARY KEY  IDENTITY (100,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
CORREO_ELECTRONICO VARCHAR(100),
FECHA_DE_NACIMIENTO DATE NOT NULL,
DNI VARCHAR(8) NOT NULL UNIQUE
)
GO

CREATE TABLE DIRECCION
(
ID_DIRECCION INT NOT NULL PRIMARY KEY IDENTITY (100,1),
CIUDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50)NOT NULL, 
DISTRITO VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
ID_PERSONAS INT NOT NULL
)
GO

CREATE TABLE TELEFONO
(
ID_TELEFONO INT NOT NULL PRIMARY KEY IDENTITY (100,1),
TELEFONO VARCHAR(9),
CELULAR VARCHAR(9),
ID_PERSONAS INT NOT NULL
)
GO
DROP TABLE TELEFONO;
DROP TABLE DIRECCION;
DROP TABLE PERSONAS;
go
/*
ALTER TABLE Orders
ADD FOREIGN KEY (P_Id)
REFERENCES Persons(P_Id)
*/

ALTER TABLE DIRECCION ADD CONSTRAINT DIRECCION_PERSONAS FOREIGN KEY (ID_PERSONAS) REFERENCES PERSONAS(ID_PERSONAS);
go
ALTER TABLE TELEFONO ADD CONSTRAINT TELEFONO_PERSONAS FOREIGN KEY (ID_PERSONAS) REFERENCES PERSONAS(ID_PERSONAS);
go

INSERT INTO PERSONAS(NOMBRE, APELLIDO, CORREO_ELECTRONICO, FECHA_DE_NACIMIENTO, DNI) VALUES('LUIS', 'DEL CARPIO GONSALES', 'L.GONSALES@ISUR.EDU.PE', '19900101', '24354684')
GO

INSERT INTO PERSONAS(NOMBRE, APELLIDO, CORREO_ELECTRONICO, FECHA_DE_NACIMIENTO, DNI) VALUES('IGNACIO', 'DEL MONTE MAMANI', 'I.DELMONTE@ISUR.EDU.PE', '19900502', '23658648')
GO

INSERT INTO PERSONAS(NOMBRE, APELLIDO, CORREO_ELECTRONICO, FECHA_DE_NACIMIENTO, DNI) VALUES('RODRIGO', 'CANO ZERECEDA', 'R.CANO@ISUR.EDU.PE', '19900101', '24354641')
GO

SELECT* FROM PERSONAS;
GO

INSERT INTO DIRECCION(CIUDAD, PROVINCIA, DISTRITO, DIRECCION, ID_PERSONAS) VALUES ('AREQUIPA','AREQUIPA','PAUCARPATA','CALLE LAS FLORES 200', 101)
GO

INSERT INTO DIRECCION(CIUDAD, PROVINCIA, DISTRITO, DIRECCION, ID_PERSONAS) VALUES ('AREQUIPA','AREQUIPA','PAUCARPATA','SANCHE CERRO 308', 102)
GO

INSERT INTO DIRECCION(CIUDAD, PROVINCIA, DISTRITO, DIRECCION, ID_PERSONAS) VALUES ('AREQUIPA','AREQUIPA','PAUCARPATA','AV EEUU 502', 100)
GO

SELECT * FROM DIRECCION;
GO

INSERT INTO DIRECCION(CIUDAD, PROVINCIA, DISTRITO, DIRECCION, ID_PERSONAS) VALUES ('AREQUIPA','AREQUIPA','PAUCARPATA','AV TORIBIO 109', 100)
GO

INSERT INTO TELEFONO(TELEFONO, CELULAR, ID_PERSONAS) VALUES('05434648','950765432',100)
GO

INSERT INTO TELEFONO(TELEFONO, CELULAR, ID_PERSONAS) VALUES('05434648','950765432',101)
INSERT INTO TELEFONO(TELEFONO, CELULAR, ID_PERSONAS) VALUES(NULL,'950095432',102)
INSERT INTO TELEFONO(TELEFONO, CELULAR, ID_PERSONAS) VALUES('05434654',NULL,102)
INSERT INTO TELEFONO(TELEFONO, CELULAR, ID_PERSONAS) VALUES(NULL,NULL,102)
GO

SELECT* FROM TELEFONO
GO



INSERT INTO DIRECCION(CIUDAD, PROVINCIA, DISTRITO, DIRECCION, ID_PERSONAS) VALUES ('AREQUIPA','AREQUIPA','SELVA ALEGRE','AV TURKO 109', 100)

--PRIMERO

CREATE PROCEDURE NUEVO_PERSONA
@NOMBRE VARCHAR(50), @APELLIDO VARCHAR(50), @CORREO_ELECTRONICO VARCHAR(100), @FECHA_DE_NACIMIENTO DATE, @DNI VARCHAR(8)
AS
BEGIN
INSERT INTO PERSONAS(NOMBRE, APELLIDO, CORREO_ELECTRONICO, FECHA_DE_NACIMIENTO, DNI) VALUES(@NOMBRE, @APELLIDO, @CORREO_ELECTRONICO, @FECHA_DE_NACIMIENTO, @DNI)
END
GO

--SEGUNDO
CREATE PROCEDURE AGREGAR_TELEFONO
@TELEFONO VARCHAR(9), @CELULAR VARCHAR(9), @ID_PERSONAS INT
AS
BEGIN
INSERT INTO TELEFONO( TELEFONO, CELULAR, ID_PERSONAS) VALUES(@TELEFONO,@CELULAR,@ID_PERSONAS)
END
GO

--TERCERO
CREATE PROCEDURE AGREGAR_DIRRECCION
@CIUDAD VARCHAR(50), @PROVINCIA VARCHAR(50), @DISTRITO VARCHAR(50), @DIRECCION VARCHAR(50),@ID_PERSONAS INT
AS
BEGIN
INSERT INTO DIRECCION(CIUDAD, PROVINCIA, DISTRITO, DIRECCION, ID_PERSONAS) VALUES(@CIUDAD,@PROVINCIA,@DISTRITO,@DIRECCION, @ID_PERSONAS)
END
GO


--réporte
create procedure REPORTE
as
begin
select p.NOMBRE  AS 'NOMBRE', p.APELLIDO AS 'APELLIDO', p.CORREO_ELECTRONICO AS 'CORREO ELECTRONICO', p.FECHA_DE_NACIMIENTO AS 'FECHA DE NACIMIENTO', p.DNI AS 'NUMERO DE  D.N.I.'
from personas p
end
go

exec REPORTE

create procedure REPORTE_TELEFONO
as
begin
select telefono AS 'TELEFONO', celular AS 'CELULAR' 
from telefono
end
go

CREATE PROCEDURE REPORTE_DIRECCION
AS
BEGIN
SELECT CIUDAD, PROVINCIA, DISTRITO, DIRECCION FROM DIRECCION
END
GO

